# Generated by Django 4.2.4 on 2023-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B.Tech.', 'B.Tech'), ('M.Tech', 'M.Tech')], default='B.Tech.', max_length=50),
            preserve_default=False,
        ),
    ]
