# Generated by Django 4.2.4 on 2023-09-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_facultycoursemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultycoursemapping',
            old_name='id',
            new_name='mappingid',
        ),
    ]
